apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: coupon
spec:
  clusterIP: None # HEADLESS SERVICE (required)
  selector:
    app: mssql
  ports:
    - port: 1433
      targetPort: 1433
      name: tcpsql
