apiVersion: v1
kind: Secret
metadata:
  name: mssql-conn-product
  namespace: product
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: >
    Server=mssql-0.mssql.coupon.svc.cluster.local,1433;
    Database=Product;
    User Id=SA;
    Password=P@ssWord123;
    Encrypt=False;
    MultipleActiveResultSets=True;
