apiVersion: v1
kind: Service
metadata:
  name: mssql-nodeport
  namespace: coupon
spec:
  type: NodePort
  selector:
    app: mssql
  ports:
    - name: tcpsql
      port: 1433
      targetPort: 1433
      nodePort: 31433
